### ISSUE TITLE
Need to support Configuration as Code plugin

### ISSUE THREAD

**Issue by jeffpearce** [jenkinsci/github-autostatus-plugin#20]

**Comment by nthienan** [comment]
I'm willing to do this. Please guide me on how to get starting or share reference documents

**Comment by jeffpearce** [comment]
HI @nthienan. Apologies for taking so long to respond. If you're still interested, there's a getting started guide here https://github.com/jenkinsci/configuration-as-code-plugin. I haven't done this before, but will do my best to answer any questions you have.

**Comment by nthienan** [comment]
Thanks, @jeffpearce. I'm still willing to support this feature. However, I'm quite busy now. Will do later

**Comment by viallikavoo** [comment]
I see that this plugin can be configured via JCasC plugin  , I used the following snippet 

`unclassified:
  BuildStatusConfig:
    credentialsId: "${CREDENTIALS_ID}"
    enableInfluxDb: true
    enableGithub: false
    influxDbDatabase: "jenkins"
    influxDbUrl: "${JENKINS_INFLUX_URL}"
`

**Comment by jeffpearce** [comment]
Hi @viallikavoo - thanks for the info. I've yet to look into what it takes to support JSasC - does this mean I should close this issue?

**Comment by viallikavoo** [comment]
Looking at the goal of this issue, it looks like this plugin can be configured using JSasC. So i think yes, you may close the issue.

**Comment by jeffpearce** [comment]
Thanks @viallikavoo. I since learned that many plugin writers are adding tests to verify JSaC compatibility, it would probably be good to have that

**Comment by darxriggs** [comment]
@nthienan are you still planning to provide a pull request for a JCasC test?

**Comment by jeffpearce** [comment]
Thanks for the reminder, @darxriggs. I will write a quick test

**Comment by darxriggs** [comment]
[PLUGINS.md](https://github.com/jenkinsci/configuration-as-code-plugin/blob/configuration-as-code-1.34/docs/PLUGINS.md#how-to-test) contains documentation on testing.

**Comment by darxriggs** [comment]
Now that #85 is merged, this issue can be closed.
