### ISSUE TITLE
Jenkins reports "Error signal" context on failure

### ISSUE THREAD

**Issue by sgleske-ias** [jenkinsci/github-autostatus-plugin#31]
When a build fails with an exception (outside of a stage I believe), then a context is voted to GitHub named `Error signal`.

When a build later succeeds all of the contexts are updated to success but `Error signal` hangs around because its status is not updated by the successful build.  This tends to confuse users and requires an explanation to a user when it happens.

`Error signal` should not be reported and should just report the overall status if there's no stage error to be reported.  I'll work on giving you a simple example so that you can replicate.

**Comment by bad2cat** [comment]
i also happen this error "Error signal" ,but no any exception. Just found this error, no other  information. 
And this error happen once in a while. How could i resolve it?

**Comment by bad2cat** [comment]
i also happen this error "Error signal" ,but no any exception. Just found this error, no other  information. 
And this error happen once in a while. How could i resolve it?

**Comment by jeffpearce** [comment]
Can you give me an example of a pipeline where this happens? The plugin is doing this intentionally, because I found some poorly written Jenkinsfiles that had sepsf outside of a stage, and I wanted to make sure errors in those got reported. But it seems like that's doing the wrong thing in your case, so if I can understand the case, I should be able to handle both cases. In retrospect, it would have been easier to fix the pipelines that were coded badly. @sgleske-ias @bad2cat

**Comment by sgleske-ias** [comment]
I'll try getting you an example this week.  In general, it shouldn't matter if a pipeline was written poorly.  The overall status of the pipeline will be reported by Jenkins as `pr-merge` or `pr-head`.  Because this will vote back `Error signal` it means that even if the pipeline passes on a second manual run (or comment trigger), the `Error signal` will still be left around.

**Comment by jeffpearce** [comment]
Ah, I see the disconnect. The reporting of ErrorSignal I added was for the part of the plugin that reports errors to an influxdb installation. This is probably *never* interesting in the context of github statuses, so I'll just ignore it for that code path. Should have a fix in a bit. Thanks for reporting

**Comment by jeffpearce** [comment]
Fixed in release 3.4.2

**Comment by sgleske-ias** [comment]
Thanks for looking at this @jeffpearce !
