### ISSUE TITLE
Could not find githubSCMSource - status will not be provided for this build

### ISSUE THREAD

**Issue by phishy** [jenkinsci/github-autostatus-plugin#32]
What plugin defines this class? I have GitHub configured in System global.

**Comment by phishy** [comment]
Upon further investigation, it seems that I needed to choose GitHub Organization over Multibranch Pipeline style of project.

**Comment by jeffpearce** [comment]
Hi @phishy. What are you trying to do with the plugin? It can do two things:
1 Provide per-stage status to your github pull requests
2 Send job and stage status to a configured influxbd rest API

If you want to use it for influxdb, you should be able to ignore the warnings, and shouldn't need to choose GH Org. I can look into whether it can work with GH org though.

**Comment by phishy** [comment]
@jeffpearce Oh it just took me a minute to realize that I had to choose GitHub Organization in order to get the stages to autoreport status to GitHub. For Multibranch Pipeline, it was throwing the error 'Could not find githubSCMSource'. Great work tho!
