### ISSUE TITLE
Enhancements Prefix and comment

### ISSUE THREAD

**Issue by damon-atkins** [jenkinsci/github-autostatus-plugin#35]
Prefix as in your example you have `deploy` it would be nice to be able to prefix it with something `<prefix>/deploy` reason being is multiple pipelines can be triggered, and if that was the case you could not tell which "setup" stage belong to which running pipeline.

The other alternative is to change the status message in the example you have
"This commit is being built"  This line could be change instead to indicate the stage e.g. `This commit is being built (<stage name>)`

**Comment by jeffpearce** [comment]
HI @damon-atkins - are you referring to the status `continuous-integration/jenkins/pr-merge - This commit is being built`? That status actually comes from the [github branch plugin source plugin](https://github.com/jenkinsci/github-branch-source-plugin/blob/master/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubNotificationContext.java#L147-L157) and shows the overall status of the entire build.  The other commit statuses in the example come from this plugin, and do include the stage name.
