### ISSUE TITLE
Adding two more fields "jobUrl" and "buildNumber" to job measurement

### ISSUE THREAD

**Issue by nthienan** [jenkinsci/github-autostatus-plugin#43]
Hi there,

I'm testing this plugin with new code changes to add 2 more fields "jobUrl" and "buildNumber" but facing an error as below:
```
2019-07-12 04:49:20.994+0000 [id=525]   WARNING o.j.p.g.n.InfluxDbNotifier#log: Could not write to influxdb - HTTP/1.1 400 Bad Request
2019-07-12 04:49:20.994+0000 [id=525]   WARNING o.j.p.g.n.InfluxDbNotifier#log: Influxdb url - http://influxdb.default.svc./write?db=jenkins&rp=autogen
2019-07-12 04:49:20.994+0000 [id=525]   WARNING o.j.p.g.n.InfluxDbNotifier#log: Series - job,jobname=DevOps/devops-sample-project/nodejs#34,owner=DevOps/devops-sample-project,repo=nodejs,branch=none,result=CompletedSuccess,blocked=0 jobtime=75701,blockedtime=0,passed=1,joburl=job/DevOps/job/devops-sample-project/job/nodejs/34/,buildnumber=34
```
I tried adding the seri by running command:
```
curl --verbose -X POST -H "Authorization: Basic xxxx=" -d  "job,jobname=DevOps/devops-sample-project/nodejs#34,owner=DevOps/devops-sample-project,repo=nodejs,branch=none,result=CompletedSuccess,blocked=0 jobtime=75701,blockedtime=0,passed=1,joburl=job/DevOps/job/devops-sample-project/job/nodejs/34/,buildnumber=34" http://influxdb.default.svc./write?db=jenkins&rp=autogen
```
then got error
```
{"error":"unable to parse 'job,jobname=DevOps/devops-sample-project/nodejs#34,owner=DevOps/devops-sample-project,repo=nodejs,branch=none,result=CompletedSuccess,blocked=0 jobtime=75701,blockedtime=0,passed=1,joburl=job/DevOps/job/devops-sample-project/job/nodejs/34/,buildnumber=34': invalid boolean"}
```
Please suggest me how to achive this! Appreciate any help!!

**Comment by jeffpearce** [comment]
Hi @nthienan. I suspect that you need to include quotes around the **joburl** field e.g.
`curl --verbose -X POST -H "Authorization: Basic xxxx=" -d  "job,jobname=DevOps/devops-sample-project/nodejs#34,owner=DevOps/devops-sample-project,repo=nodejs,branch=none,result=CompletedSuccess,blocked=0 jobtime=75701,blockedtime=0,passed=1,joburl=\"job/DevOps/job/devops-sample-project/job/nodejs/34/\",buildnumber=34" http://influxdb.default.svc./write?db=jenkins&rp=autogen
`

**buildnumber** should be fine (assuming you want it to be an int), but if not you could quote that too. [More info ](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/)

FWIW, I'm thinking about trying to change the schema - the existing schema has too many tags, and so doesn't perform well. I'm testing that change locally, and then trying to figure out how best to roll it out. Migrating data is tough in influxdb (though it can be done). It doesn't affect what you're doing, since you're adding fields.

Let me know if this helps.

Let me

**Comment by nthienan** [comment]
Thanks, @jeffpearce. Your suggestion is great. It works now.

Regarding changing schema, could you share more info about schema that you could change to? It may impact to our work since I'm building a Grafana dashboard based on current schema.

BTW, what do you think if **buildNumber** is a tag instead of a field? My problem is when visualization, job name is too long then make a confusing dashboard. Hence, I want to use build number as an alternative. 
![image](https://user-images.githubusercontent.com/10244759/61194264-92628900-a6ea-11e9-90b3-b8e329386825.png)

**Comment by jeffpearce** [comment]
Hi @nthienan. Here's my current thinking for:
job https://github.com/jenkinsci/github-autostatus-plugin/blob/schema/src/main/java/org/jenkinsci/plugins/githubautostatus/notifiers/InfluxDbNotifier.java#L204-L214
stage https://github.com/jenkinsci/github-autostatus-plugin/blob/schema/src/main/java/org/jenkinsci/plugins/githubautostatus/notifiers/InfluxDbNotifier.java#L175-L184

I'd like to hear your feedback on this. The old schema had some issues because it included high cardinality fields such as jobname as tags, which was causing the server to decline greatly over time. The new approach is to include only properties with lower cardinality as tags, and make everything else fields

**Comment by jeffpearce** [comment]
> BTW, what do you think if buildNumber is a tag instead of a field? My problem is when visualization, job name is too long then make a confusing dashboard

Adding it makes sense, but would it work just as well as a field?

**Comment by nthienan** [comment]
> I'd like to hear your feedback on this. The old schema had some issues because it included high cardinality fields such as jobname as tags, which was causing the server to decline greatly over time. The new approach is to include only properties with lower cardinality as tags, and make everything else fields

New schema looks fine to me. Willing to get a try when it's released.

>  > BTW, what do you think if buildNumber is a tag instead of a field? My problem is when visualization, job name is too long then make a confusing dashboard
> 
> Adding it makes sense, but would it work just as well as a field?

No, it wouldn't. My concern, however, as you say, high cardinality tags cause performance issues. What do you think?

**Comment by jeffpearce** [comment]
@nthienan I'd strongly suggest not making it a tag. "Performance issue" is probably even an understatement. High cardinality will eventually cause the server to start rejecting requests. You might be able to mitigate it with retention policies by only keeping the most recent data.

Can you tell me how you want to use it? I've found that although the grafana query builder has limitations around fields, you can get over much of them by editing the query directly. It's not ideal, but it works :-) I'm happy to help in any way I can

**Comment by nthienan** [comment]
> Can you tell me how you want to use it?

Here is my current query: 
```
SELECT "jobtime" FROM "job" WHERE ("owner" =~ /^$folder$/ AND "repo" =~ /^$job$/) AND $timeFilter GROUP BY "buildnumber"
```
which produces a graph as picture below
![image](https://user-images.githubusercontent.com/10244759/61425017-aeab3380-a93f-11e9-95bd-5a2efa8c084e.png)
I don't know how to group build duration by build if we don't have build number or job name as a tag. Appreciate any suggestions.

**Comment by nthienan** [comment]
@jeffpearce any idea/suggestion?

**Comment by jeffpearce** [comment]
Hi @nthienan sorry for the delayed response. My first reaction is that adding build number could explode cardinality, but it depends on how many repos the plugin is collecting stats about.

I wonder whether you could aggregate by time instead? It's not as nice a display, but I think it might achieve the same result.

Another thing I'm pondering is adding the ability to control some of the schema in some cases - I'd keep a safe default, but allow the ability to make things tags for certain installations. That's a lot more work though :-)

Thoughts?

**Comment by jeffpearce** [comment]
Allowing control of the schema also might help solve the problem of how to migrate people from the old to the new - they could just not worry about it until they need to

**Comment by nthienan** [comment]
> Hi @nthienan sorry for the delayed response. My first reaction is that adding build number could explode cardinality, but it depends on how many repos the plugin is collecting stats about.
> I wonder whether you could aggregate by time instead? It's not as nice a display, but I think it might achieve the same result.

Thank you for response, @jeffpearce. I'm building a CI/CD dashboard for my organization. The organization has hundreds of repo/job and continue to grow. I don't want to deal with high cardinality issue since it's really serious. Maybe I will remove build duration graph, just have only avg build duration.

> Allowing control of the schema also might help solve the problem of how to migrate people from the old to the new - they could just not worry about it until they need to

It's great to have such feature. Is it possible to release new schema first, then adding ability to control schema later? I would like to use the official release of this plugin in my system rather than the private one built by me.

**Comment by nthienan** [comment]
One more thing, could you add job URL and build number as fields in all measurements. Actually, I can open a PR for that, but the schema and code structure are changing. So I want to avoid conflicting.

**Comment by jeffpearce** [comment]
I’m happy too, you can also send a pr against the branch with the schematic changes

Sent from my iPhone

On Jul 25, 2019, at 8:11 PM, An Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:

Notice: This email is from an external sender.



One more thing, could you add job URL and build number as fields in all measurements. Actually, I can open a PR for that, but the schema and code structure are changing. So I want to avoid conflicting.

**Comment by jeffpearce** [comment]
HI @nthienan. I'm going to try to get the schema update out this week. I'm happy to add these two new fields

**Comment by nthienan** [comment]
@jeffpearce  #46 is opened, please review

**Comment by nthienan** [comment]
@jeffpearce what is plan for next release? I'm waiting for it.

**Comment by jeffpearce** [comment]
Hi @nthienan - I've been overbooked lately, but I promise I'll get this out as soon as I can. I appreciate all the work you've done for this plugin

**Comment by mayaaravotwm** [comment]
Hey @nthienan is it possible that you will share with me your dashboard please?

**Comment by nthienan** [comment]
> Hey @nthienan is it possible that you will share with me your dashboard please?

Sorry, I can't. However, I'm happy to answer your questions/concerns. 
One thing to be noticed, I don't use InfluxDB as a data source for my dashboards. I use MariaDB instead.

**Comment by nthienan** [comment]
@mayaaravotwm 
I can share pictures of my dashboards, but not dashboard's JSON

**Build overall dashboard**
![1](https://user-images.githubusercontent.com/10244759/71455182-8bc25c80-27c6-11ea-9aab-7dfb89eca6df.png)
![2](https://user-images.githubusercontent.com/10244759/71455320-1014df80-27c7-11ea-9469-76456ec919fe.png)
![3](https://user-images.githubusercontent.com/10244759/71455195-91b83d80-27c6-11ea-8a61-95ef1922b85e.png)

**Build details dashboard**
![4](https://user-images.githubusercontent.com/10244759/71455198-941a9780-27c6-11ea-9f76-0498d5767f14.png)
![5](https://user-images.githubusercontent.com/10244759/71455201-967cf180-27c6-11ea-8368-e7c363cf4145.png)
![6](https://user-images.githubusercontent.com/10244759/71455203-9977e200-27c6-11ea-857a-875882b33270.png)
![7](https://user-images.githubusercontent.com/10244759/71455207-9bda3c00-27c6-11ea-8a46-0e0f4372fe24.png)

**Comment by s-kelvin** [comment]
In InfluxDB you cannot group by a field so after you changed "buildnumber" from a tag to field, we can no longer use it as a tag to generate the same build duration graph above. Is there any workaround?
