### ISSUE TITLE
Distinguish ABORT and FAILURE 

### ISSUE THREAD

**Issue by link89** [jenkinsci/github-autostatus-plugin#51]
When a job is terminated, we can only get one of  `CompletedError` and `CompletedSuccess`
I hope that there is a way we can tell whether it is ABORT or  FAILURE when the result is error.

For aborted job, we hope the result to be `CompletedAborted`

If you think this proposal is reasonable, we can try to create a PR for it.

**Comment by jeffpearce** [comment]
Hi @link89 . That sounds useful to me. Please submit a PR

**Comment by darxriggs** [comment]
Hi @link89 did you already make some progress with your PR?

**Comment by jeffpearce** [comment]
I was able to add this since I'm refactoring the error resolution stuff to correctly handle caught errors.  Should be in next release

**Comment by jeffpearce** [comment]
Please try release 3.6.1 and let me know if you are still having issues
