### ISSUE TITLE
Avoid raw passwords in plugin configuration

### ISSUE THREAD

**Issue by harlowja** [jenkinsci/github-autostatus-plugin#7]
It seems common that plugins start off by having passwords that people present directly to the plugin; then a plugin realizes that jenkins has a credential store that should be used instead of a direct password. I've seen this realization in the github plugin, the openstack clouds plugin and a few others. So likely the same needs to be done here for the `influx_db_password` in that it should just reference a thing in the credentials store (even though that thing is not super-secure, it does appear to be best practice at least).

**Comment by jeffpearce** [comment]
@harlowja Thanks for reporting this. It's fixed in pending release 3.0
