### ISSUE TITLE
Github PR Status Using Retry Options 

### ISSUE THREAD

**Issue by shaharon** [jenkinsci/github-autostatus-plugin#77]
I got a declarative Jenkinsfile set to use "retry option", and while stage command failed on first try, Github PR status it set to failed despite the fact that command is passed on second or third attempts.

**Example**:

stage('Stage1') {
  options { retry(3) }
  steps {
    sh 'some-command'
  }
}

**Comment by shaharon** [comment]
Anyone?

**Comment by jeffpearce** [comment]
I'll take a look.

**Comment by jeffpearce** [comment]
Hi @shaharon - can you let me know whether it's working with the 3.6.1 release? I didn't fix it intentionally, but I reworked the way the code determines statuses, and I'm now unable to repro it

**Comment by shaharon** [comment]
@jeffpearce - Thanks for that, currently use 3.6.0, will upgrade to 3.6.1 and let you know.

**Comment by shaharon** [comment]
@jeffpearce - Looks great using version 3.6.1. Thanks!
