### ISSUE TITLE
Failed to send data from build to influxDB, when another build already sending data

### ISSUE THREAD

**Issue by krolol** [jenkinsci/github-autostatus-plugin#78]
![image](https://user-images.githubusercontent.com/33641729/70229359-1fc07b80-1767-11ea-8781-992c21f47ee6.png)

**Comment by jeffpearce** [comment]
🙀 I'll look into this ASAP

**Comment by jeffpearce** [comment]
I can't repro this, but I think #82 should fix it. Let me know if you're still seeing after the next release
